plugins:
  - rubocop-rails

AllCops:
  CacheRootDirectory: tmp/rubocop_cache
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "typed_rails_enum_keys.gemspec"
    - "spec/**/*"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 20

Rails/Output:
  Exclude:
    - "lib/typed_rails_enum_keys/tasks.rb"

Rails/Exit:
  Exclude:
    - "lib/typed_rails_enum_keys/tasks.rb"
