# frozen_string_literal: true

RSpec.describe RailsEnumBridge::TypeScript::ModelFile do
  it "generates const objects, union types, and a deterministic schema hash" do
    definition = RailsEnumBridge::EnumDefinition.new(
      model_name: "Task",
      model_export_name: "Task",
      attribute_name: "work_priority",
      rails_mapping_name: "work_priorities",
      typescript_property_name: "workPriorities",
      typescript_type_name: "TaskWorkPriority",
      values: %w[priority_1 priority_2]
    )

    first = described_class.new(model_export_name: "Task", definitions: [definition]).render
    second = described_class.new(model_export_name: "Task", definitions: [definition]).render

    expect(first).to eq(second)
    expect(first).to include("// AUTO-GENERATED BY rails_enum_bridge. DO NOT EDIT.")
    expect(first).to match(%r{// enum-schema-sha256: [a-f0-9]{64}})
    expect(first).to include('workPriorities: ["priority_1", "priority_2"],')
    expect(first).to include("export type TaskWorkPriority = (typeof Task.workPriorities)[number];")
  end
end
