# frozen_string_literal: true

require "digest"
require "json"

module TypedEnums
  module TypeScript
    class ModelFile
      HEADER = "// AUTO-GENERATED BY typed_enums. DO NOT EDIT."

      def initialize(model_export_name:, definitions:)
        @model_export_name = model_export_name
        @definitions = definitions
      end

      def render
        <<~TYPESCRIPT
          #{HEADER}
          // enum-schema-sha256: #{schema_hash}

          export const #{model_export_name} = {
          #{property_lines}
          } as const;

          #{type_lines}
        TYPESCRIPT
      end

      private

      attr_reader :model_export_name, :definitions

      def property_lines
        definitions.map do |definition|
          "  #{definition.typescript_property_name}: #{render_array(definition.values)},"
        end.join("\n")
      end

      def type_lines
        definitions.map do |definition|
          "export type #{definition.typescript_type_name} = " \
            "(typeof #{model_export_name}.#{definition.typescript_property_name})[number];"
        end.join("\n")
      end

      def render_array(values)
        "[#{values.map { |value| JSON.generate(value) }.join(', ')}]"
      end

      def schema_hash
        Digest::SHA256.hexdigest(JSON.generate(schema))
      end

      def schema
        {
          model: model_export_name,
          enums: definitions.map do |definition|
            {
              attribute: definition.attribute_name,
              rails_mapping: definition.rails_mapping_name,
              property: definition.typescript_property_name,
              type: definition.typescript_type_name,
              values: definition.values
            }
          end
        }
      end
    end
  end
end
