# frozen_string_literal: true

RSpec.describe TypedEnums::TypeScript::IndexFile do
  it "generates deterministic sorted barrel exports" do
    content = described_class.new(model_export_names: %w[Task BoardColumn]).render

    expect(content).to eq(<<~TYPESCRIPT)
      // AUTO-GENERATED BY typed_enums. DO NOT EDIT.

      export * from "./BoardColumn";
      export * from "./Task";
    TYPESCRIPT
  end
end
