# frozen_string_literal: true

RSpec.describe TypedEnums::Output::JavaScriptFile do
  it "generates one deterministic JavaScript module with a schema hash" do
    definition = TypedEnums::EnumDefinition.new(
      model_name: "Task",
      model_export_name: "Task",
      attribute_name: "work_priority",
      rails_mapping_name: "work_priorities",
      typescript_property_name: "workPriorities",
      typescript_type_name: "TaskWorkPriority",
      values: %w[priority_1 priority_2]
    )

    first = described_class.new(model_groups: { "Task" => [definition] }).render
    second = described_class.new(model_groups: { "Task" => [definition] }).render

    expect(first).to eq(second)
    expect(first).to include("// AUTO-GENERATED BY typed_enums. DO NOT EDIT.")
    expect(first).to match(%r{// enum-schema-sha256: [a-f0-9]{64}})
    expect(first).to include("export const Task = {")
    expect(first).to include('workPriorities: ["priority_1", "priority_2"],')
    expect(first).not_to include("export type")
  end
end
