# frozen_string_literal: true

RSpec.describe TypedEnums::Output::TypeDeclarationFile do
  it "generates TypeScript declarations for the JavaScript module" do
    definition = TypedEnums::EnumDefinition.new(
      model_name: "Task",
      model_export_name: "Task",
      attribute_name: "work_priority",
      rails_mapping_name: "work_priorities",
      typescript_property_name: "workPriorities",
      typescript_type_name: "TaskWorkPriority",
      values: %w[priority_1 priority_2]
    )

    content = described_class.new(
      model_groups: { "Task" => [definition] },
      schema_hash: "abc123"
    ).render

    expect(content).to include("// AUTO-GENERATED BY typed_enums. DO NOT EDIT.")
    expect(content).to include("// enum-schema-sha256: abc123")
    expect(content).to include("export declare const Task: {")
    expect(content).to include('readonly workPriorities: readonly ["priority_1", "priority_2"];')
    expect(content).to include("export type TaskWorkPriority = (typeof Task.workPriorities)[number];")
  end
end
