# frozen_string_literal: true

require "digest"
require "json"

module TypedEnums
  module Output
    class JavaScriptFile
      HEADER = "// AUTO-GENERATED BY typed_enums. DO NOT EDIT."

      def initialize(model_groups:)
        @model_groups = model_groups
      end

      def render
        <<~JAVASCRIPT
          #{HEADER}
          // enum-schema-sha256: #{schema_hash}

          #{model_exports}
        JAVASCRIPT
      end

      def schema_hash
        Digest::SHA256.hexdigest(JSON.generate(schema))
      end

      private

      attr_reader :model_groups

      def model_exports
        model_groups.map do |model_export_name, definitions|
          <<~JAVASCRIPT.chomp
            export const #{model_export_name} = {
            #{property_lines(definitions)}
            };
          JAVASCRIPT
        end.join("\n\n")
      end

      def property_lines(definitions)
        definitions.map do |definition|
          "  #{definition.typescript_property_name}: #{render_array(definition.values)},"
        end.join("\n")
      end

      def render_array(values)
        "[#{values.map { |value| JSON.generate(value) }.join(', ')}]"
      end

      def schema
        model_groups.transform_values do |definitions|
          definitions.map do |definition|
            {
              attribute: definition.attribute_name,
              rails_mapping: definition.rails_mapping_name,
              property: definition.typescript_property_name,
              type: definition.typescript_type_name,
              values: definition.values
            }
          end
        end
      end
    end
  end
end
